 # This is a basic workflow to help you get started with Actions

name: CI XXX

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Sets up .NET Core SDK 6.0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with: 
           dotnet-version: 6.0.x

      # Publishes the Blazor project to the release folder
      - name: Publish .NET Core Project
        run: dotnet publish /samples/json-to-csv/OnlineConverterBlazorApp/OnlineConverterBlazorApp/OnlineConverterBlazorApp.csproj -c Release -o release –nologo
        
        
      - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
        run: sed -i ‘s/<base href=”\/” \/>/<base href=”\/BlazorGitHubPagesDemo\/” \/>/g’ release/wwwroot/index.html
        
        # Copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # Add the .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
